### ISSUE TITLE
Support for a "raw" result reading of exiftool output

### ISSUE THREAD

**Issue by camlegleiter** [mceachen/exiftool-vendored.js#35]
**Is your feature request related to a problem? Please describe.**
I'm looking to extract the EXIF tags from a number of images and write the tags for each image into a separate XML file.

**Describe the solution you'd like**
A separate API like `exiftool.readRaw(path[, options])` that allows for flags like `-X` to return just the RAW (or in this case, XML) output as a string/Buffer that could then be interacted with.

**Describe alternatives you've considered**
1. Manually converting the Tags object to XML and writing that to a file, which has the downside of
  a. Overhead of `exiftool-vendored.js` parsing the JSON output, and
  b. Re-converting the Tags to XML and attempting to match the same structure `exiftool.pl` has
2. Using a different NPM module, though I like the `exiftool-vendored.js` performance and handling of processes.
3. Using `exiftool.pl` directly, either through `exiftool-vendored.pl` or a direct install, though I'd like to avoid re-inventing this module, and for the same reasons as above.

**Comment by mceachen** [comment]
The main (only?) value-add of this project is to provide parsing and single-file read/write operations via batch-cluster. Your usecase isn't parsing, and wants to hit large file subdirectories. ExifTool has extensive batch operations that should make this a one-liner!

 See https://sno.phy.queensu.ca/~phil/exiftool/mistakes.html

You can still use [exiftool-vendored.exe](https://github.com/mceachen/exiftool-vendored.exe) or [exiftool-vendored.pl](https://github.com/mceachen/exiftool-vendored.pl) to get the latest version of ExifTool installed on your server, but instead of using this module, just `exec` exiftool with the correct batch args.

**Comment by camlegleiter** [comment]
Thanks, this was exactly what I needed. Definitely helps to read the documentation :)

I was able to utilize exiftool-vendored.pl to get what appears to be a working solution to write each image's EXIF data as XML to a similarly named file via:
```shell
$ exiftool -X -w output/%f.xml -ext <ext> <dir>
```
which works much better and is definitely faster.

To your point, I don't see a need for an API like this, and definitely don't want to add any confusion to the purpose of the library. It's nice to have an easy wrapper through a library like this so writing manual `exec` code isn't as necessary, but I'll get over it. Thanks again!

**Comment by mceachen** [comment]
Great, thanks for taking the time to say it worked! I'll add a reference to this issue to the wiki.

**Comment by daz** [comment]
What about having `extractBinaryTag` to a buffer? Or would you suggest just using a tmpfile?

**Comment by mceachen** [comment]
Please read the second and third comment.
